In [29]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.impute import SimpleImputer  # For handling missing values (if needed)
from sklearn.preprocessing import OneHotEncoder  # For categorical encoding

# Optional for visualization (if desired)
import matplotlib.pyplot as plt

Random Forest on Dataset with Outliers

In [30]:
#loading dataset with outliers only 


# Read Excel file into DataFrame
df_outliers = pd.read_excel('../Data_Set/new_df_outliers_only_copy_smote_resampled.xlsx')

# Display the DataFrame
df_outliers

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,smoking_history_encoded,gender_encoded,diabetes
0,0.174516,0,0,0.930849,-0.357602,-1.154539,1.806645,-0.777719,0
1,-1.018012,0,0,1.073804,-0.233789,0.206884,-0.280453,-0.777719,0
2,0.949660,0,0,1.656370,1.375782,-0.405756,-0.280453,-0.777719,1
3,-0.779506,0,0,1.006045,-0.048069,-0.746112,-0.280453,1.417943,0
4,-1.256518,0,0,0.553214,-0.357602,-1.154539,-1.553924,-0.777719,0
...,...,...,...,...,...,...,...,...,...
6163,0.449954,0,0,0.397771,-0.410728,-0.364914,-0.280453,-0.777719,0
6164,-0.874241,0,0,0.341732,-1.100480,-0.786955,-1.030285,-0.777719,0
6165,-2.108582,0,0,0.585866,-0.225281,-1.399595,-1.009532,-0.777719,0
6166,-0.640560,0,0,0.629500,-0.108843,-0.405756,-1.133316,-0.052526,0
6167,0.591901,0,0,1.627652,-1.001929,-0.364914,0.629038,1.417943,0

In [31]:
num_rows = df_outliers.shape[0]

print("Number of rows in the DataFrame:", num_rows)

Number of rows in the DataFrame: 6168

In [39]:
#Splitting data into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#training set: this is the larger portion of the data (usually 80%) used to train the machine learning model. the model learns patterns and relationships from the training data 

#testing set: this is the smaller portion of the data (usually 20%) used to evaluate the model's performance. the model makes predictions on the testing data and the predictions are compared to the actual target values to evaluate the model's performance.

NameError: name 'X' is not defined

In [ ]:
#create and train the random forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

NameError: name 'X_train' is not defined

Random Forest on Dataset without Outliers

In [ ]:

# Read Excel file into DataFrame
df_without_outliers = pd.read_excel('../Data_Set/new_df_without_outliers_copy_smote_resampled.xlsx')

# Display the DataFrame
df_without_outliers

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,smoking_history_encoded,gender_encoded,diabetes
0,1.349487,0,1,-0.580455,0.629251,-0.317312,0.263730,-0.974068,0
1,0.149555,0,0,-0.241118,0.629251,-1.649552,-1.579747,-0.974068,0
2,-1.050377,0,0,-0.241118,-0.272192,0.082360,0.263730,1.211318,0
3,-0.681167,0,0,-0.857661,-0.973313,0.015748,0.331039,-0.974068,0
4,1.164882,1,1,-1.384988,-1.173634,0.015748,0.331039,1.211318,0
...,...,...,...,...,...,...,...,...,...
181139,1.349487,0,0,-0.261522,0.979109,-0.628168,1.103451,1.211318,1
181140,1.349487,0,0,-0.241118,-0.172031,0.015748,0.624467,-0.399610,1
181141,-0.727318,0,0,-0.241061,1.025419,0.104564,0.763605,1.211318,1
181142,0.334160,0,0,-0.241118,0.045409,0.015748,-1.579747,1.211318,1
181143,1.349487,1,0,-0.164762,0.192374,2.347168,0.263730,-0.578758,1

In [ ]:
num_rows = df_without_outliers.shape[0]

print("Number of rows in the DataFrame:", num_rows)

Number of rows in the DataFrame: 181144